"""
OpenClaw V7 — AI Cycle Predictor
=================================
LSTM-based forward prediction of the CycleDetector composite score.

Design rationale
----------------
The existing CycleDetector computes a *current* composite score across 9 Dewey-
style cycles.  This module adds a forward-looking layer:

  1. Training data is generated by replaying CycleDetector.evaluate() across
     the past N years, one tick per day, with no live API calls
     (funding = neutral, rotation = neutral).  This captures the 7 fully
     deterministic cycles (halving phase, monthly seasonality, day-of-week,
     hour-of-day, lunar, quarterly opex, solar).

  2. An LSTM learns: "given the past SEQ_LEN days of per-cycle scores, what
     will the composite look like HORIZON days from now?"

  3. At inference, we pass the last SEQ_LEN days of *real* composites
     (including live funding / rotation) and get back a predicted composite.
     If predicted composite > BULLISH_THRESHOLD → cycles are aligned ahead.

  4. CycleAIPredictor is an *optional* enhancement — MemeCoinScanner falls back
     gracefully to the standard CycleDetector if no checkpoint exists.

Training cost: ~15-25 s on CPU for 4-year history, 60 epochs.
Checkpoint:   data/ai_cycle_predictor.pth

Usage
-----
    predictor = CycleAIPredictor()
    predictor.generate_and_train()          # once, then weekly
    is_bullish = predictor.is_cycle_bullish(horizon_days=30)
"""
from __future__ import annotations

import json
import warnings
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import List, Optional, Tuple

import numpy as np

warnings.filterwarnings("ignore")

# ── optional heavy deps ───────────────────────────────────────────────────────
try:
    import torch
    import torch.nn as nn
    import torch.optim as optim
    from torch.utils.data import DataLoader, Dataset
    _TORCH_AVAILABLE = True
except ImportError:
    _TORCH_AVAILABLE = False

# CycleDetector imported lazily to avoid circular issues at module load
CYCLE_DETECTOR_CLS = None

def _get_cycle_detector_cls():
    global CYCLE_DETECTOR_CLS
    if CYCLE_DETECTOR_CLS is None:
        from core.cycle_detector import CycleDetector
        CYCLE_DETECTOR_CLS = CycleDetector
    return CYCLE_DETECTOR_CLS


# ── constants ─────────────────────────────────────────────────────────────────

SEQ_LEN          = 60      # days of history fed into LSTM
HORIZON_DEFAULT  = 30      # days ahead to predict
HIDDEN_SIZE      = 64      # LSTM hidden units
NUM_LAYERS       = 2
DROPOUT          = 0.15
BATCH_SIZE       = 32
DEFAULT_EPOCHS   = 60
DEFAULT_LR       = 8e-4
BULLISH_THRESHOLD  = 0.25  # predicted composite > this → tailwind ahead
BEARISH_THRESHOLD  = -0.25

# N_SIGNALS must match the number of CycleSignal objects returned by CycleDetector.evaluate()
# V7.5: halving, monthly, dow, hour, lunar, opex, solar, funding, rotation = 9
#        + kondratiev_wave, juglar_cycle, kitchin_cycle = 3  →  total 12
# NOTE: any existing checkpoint (data/ai_cycle_predictor.pth) trained on 9 signals
# will fail to load after this change. Delete the file and retrain:
#   python -m core.cycle_ai_predictor --years 4 --epochs 60
N_SIGNALS = 12

# ── LSTM model ────────────────────────────────────────────────────────────────

class _CycleLSTM(nn.Module if _TORCH_AVAILABLE else object):
    """Tiny LSTM: (batch, seq, n_signals) → (batch, 1) predicted composite."""

    def __init__(self, input_size: int = N_SIGNALS, hidden: int = HIDDEN_SIZE,
                 layers: int = NUM_LAYERS, dropout: float = DROPOUT):
        if not _TORCH_AVAILABLE:
            raise RuntimeError("PyTorch is required. pip install torch")
        super().__init__()
        self.lstm = nn.LSTM(input_size, hidden, layers,
                            batch_first=True, dropout=dropout)
        self.head = nn.Sequential(
            nn.Linear(hidden, 32),
            nn.GELU(),
            nn.Linear(32, 1),
            nn.Tanh(),   # output in [-1, 1], matching composite range
        )

    def forward(self, x):
        out, _ = self.lstm(x)
        return self.head(out[:, -1, :])


# ── dataset ───────────────────────────────────────────────────────────────────

class _CycleDataset(Dataset if _TORCH_AVAILABLE else object):
    def __init__(self, signal_matrix: np.ndarray, composites: np.ndarray,
                 seq_len: int, horizon: int):
        if not _TORCH_AVAILABLE:
            raise RuntimeError("PyTorch required.")
        super().__init__()
        xs, ys = [], []
        T = len(composites)
        for i in range(T - seq_len - horizon + 1):
            xs.append(signal_matrix[i : i + seq_len])           # (seq, n_sig)
            ys.append(composites[i + seq_len + horizon - 1])    # scalar
        self.X = torch.tensor(np.array(xs), dtype=torch.float32)
        self.y = torch.tensor(np.array(ys), dtype=torch.float32).unsqueeze(1)

    def __len__(self):  return len(self.X)
    def __getitem__(self, i): return self.X[i], self.y[i]


# ── main class ────────────────────────────────────────────────────────────────

class CycleAIPredictor:
    """
    Trains and runs an LSTM on CycleDetector history to predict future
    cycle composite scores N days ahead.

    Parameters
    ----------
    checkpoint_path : str
        Where to save / load the PyTorch model weights.
    history_cache_path : str
        JSON cache of generated historical composite sequences.
    seq_len : int
        Rolling window fed into LSTM (days).
    horizon : int
        How many days ahead to predict.
    """

    def __init__(
        self,
        checkpoint_path: str = "data/ai_cycle_predictor.pth",
        history_cache_path: str = "data/cycle_history_cache.json",
        seq_len: int = SEQ_LEN,
        horizon: int = HORIZON_DEFAULT,
    ):
        self.checkpoint_path = Path(checkpoint_path)
        self.history_cache_path = Path(history_cache_path)
        self.seq_len = seq_len
        self.horizon = horizon

        self.model: Optional[_CycleLSTM] = None
        self._signal_history: List[List[float]] = []   # list of per-day signal vectors
        self._composite_history: List[float] = []

        if self.checkpoint_path.exists() and _TORCH_AVAILABLE:
            self._load_model()

        # Try to prime recent history from cache
        self._load_history_cache()

    # ── history generation ────────────────────────────────────────────────────

    def generate_history(self, years: int = 4, verbose: bool = True) -> Tuple[np.ndarray, np.ndarray]:
        """
        Replay CycleDetector across historical dates (deterministic cycles only —
        no live API calls).

        Returns
        -------
        signal_matrix : np.ndarray  shape (T, N_SIGNALS)
        composites    : np.ndarray  shape (T,)
        """
        CycleDetector = _get_cycle_detector_cls()

        # Construct a no-API-call detector instance
        det = object.__new__(CycleDetector)
        det.bybit_symbol = "ETHUSDT"
        det._http = None   # disables funding and rotation live fetches

        end   = datetime.now(timezone.utc).replace(hour=14, minute=0, second=0, microsecond=0)
        start = end - timedelta(days=365 * years)

        signals_list: List[List[float]] = []
        composites: List[float] = []

        if verbose:
            print(f"[CycleAI] Generating {(end - start).days} days of cycle history…")

        current = start
        day = 0
        while current <= end:
            comp = det.evaluate(now=current)
            signals_list.append([s.score for s in comp.signals])
            composites.append(comp.composite)
            current += timedelta(days=1)
            day += 1
            if verbose and day % 365 == 0:
                print(f"  {day // 365}yr done  composite range [{min(composites):.3f}, {max(composites):.3f}]")

        sig_arr  = np.array(signals_list, dtype=np.float32)
        comp_arr = np.array(composites,   dtype=np.float32)

        self._signal_history   = signals_list
        self._composite_history = composites
        self._save_history_cache()

        if verbose:
            print(f"[CycleAI] History ready: {len(composites)} days  "
                  f"mean={np.mean(comp_arr):.3f}  std={np.std(comp_arr):.3f}")
        return sig_arr, comp_arr

    # ── training ─────────────────────────────────────────────────────────────

    def train(
        self,
        signal_matrix: Optional[np.ndarray] = None,
        composites:    Optional[np.ndarray] = None,
        years: int   = 4,
        epochs: int  = DEFAULT_EPOCHS,
        lr: float    = DEFAULT_LR,
        verbose: bool = True,
    ) -> None:
        """
        Train the LSTM.  If signal_matrix / composites are not provided, calls
        generate_history() automatically.
        """
        if not _TORCH_AVAILABLE:
            raise RuntimeError("pip install torch  before training.")

        if signal_matrix is None or composites is None:
            signal_matrix, composites = self.generate_history(years=years, verbose=verbose)

        n_signals = signal_matrix.shape[1]
        dataset   = _CycleDataset(signal_matrix, composites, self.seq_len, self.horizon)
        loader    = DataLoader(dataset, batch_size=BATCH_SIZE, shuffle=True, drop_last=True)

        model     = _CycleLSTM(input_size=n_signals)
        optimizer = optim.AdamW(model.parameters(), lr=lr, weight_decay=1e-4)
        scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=epochs)
        criterion = nn.MSELoss()

        if verbose:
            print(f"[CycleAI] Training LSTM  {n_signals}→{HIDDEN_SIZE}→1  "
                  f"seq={self.seq_len}  horizon={self.horizon}d  "
                  f"samples={len(dataset)}  epochs={epochs}")

        for epoch in range(1, epochs + 1):
            model.train()
            total = 0.0
            for X, y in loader:
                optimizer.zero_grad()
                loss = criterion(model(X), y)
                loss.backward()
                nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                optimizer.step()
                total += loss.item()
            scheduler.step()
            if verbose and (epoch % 10 == 0 or epoch == epochs):
                print(f"  epoch {epoch:>3}/{epochs}  loss={total/len(loader):.5f}")

        self.model = model
        self.model.eval()
        self._save_model()
        if verbose:
            print(f"[CycleAI] ✅ Trained and saved → {self.checkpoint_path}")

    def generate_and_train(self, years: int = 4, epochs: int = DEFAULT_EPOCHS,
                           verbose: bool = True) -> None:
        """Convenience: generate history then train."""
        sig, comp = self.generate_history(years=years, verbose=verbose)
        self.train(signal_matrix=sig, composites=comp, epochs=epochs, verbose=verbose)

    # ── inference ─────────────────────────────────────────────────────────────

    def predict_composite(
        self,
        recent_signals: Optional[List[List[float]]] = None,
    ) -> float:
        """
        Predict the cycle composite score HORIZON days ahead.

        Parameters
        ----------
        recent_signals : list of lists, shape (SEQ_LEN, N_SIGNALS)
            Most recent SEQ_LEN days of per-signal scores.
            If None, uses cached history (auto-generated if missing).

        Returns
        -------
        float
            Predicted composite in [-1, 1].  Positive = bullish.
        """
        if not _TORCH_AVAILABLE:
            return 0.0
        if self.model is None:
            return 0.0

        if recent_signals is None:
            # Use cached history; generate if missing or too short
            if len(self._signal_history) < self.seq_len:
                self.generate_history(verbose=False)
            recent_signals = self._signal_history[-self.seq_len :]

        # Append today's live reading if we have a real detector
        if len(recent_signals) < self.seq_len:
            # Pad with zeros (neutral)
            pad = [[0.0] * N_SIGNALS] * (self.seq_len - len(recent_signals))
            recent_signals = pad + list(recent_signals)

        x = torch.tensor([recent_signals[-self.seq_len :]], dtype=torch.float32)
        with torch.no_grad():
            pred = self.model(x).item()
        return float(np.clip(pred, -1.0, 1.0))

    def is_cycle_bullish(
        self,
        horizon_days: Optional[int] = None,
        recent_signals: Optional[List[List[float]]] = None,
        threshold: float = BULLISH_THRESHOLD,
    ) -> bool:
        """
        Returns True if the AI predicts a bullish (tailwind) cycle ahead.
        Falls back to False if the model is not trained.
        """
        if self.model is None:
            return False  # safe default — no model → don't gate

        if horizon_days and horizon_days != self.horizon:
            # Can't change horizon post-training without re-training; use best proxy
            pass

        pred = self.predict_composite(recent_signals=recent_signals)
        return pred >= threshold

    def get_prediction_summary(
        self, recent_signals: Optional[List[List[float]]] = None
    ) -> dict:
        """Return a rich dict for logging / Telegram alerts."""
        if self.model is None:
            return {"trained": False, "predicted_composite": None, "sentiment": "UNKNOWN"}

        pred = self.predict_composite(recent_signals=recent_signals)
        if pred >= BULLISH_THRESHOLD:
            sentiment = "TAILWIND_AHEAD"
        elif pred <= BEARISH_THRESHOLD:
            sentiment = "HEADWIND_AHEAD"
        else:
            sentiment = "NEUTRAL_AHEAD"

        return {
            "trained": True,
            "horizon_days": self.horizon,
            "predicted_composite": round(pred, 4),
            "sentiment": sentiment,
            "bullish": pred >= BULLISH_THRESHOLD,
        }

    # ── live history update ───────────────────────────────────────────────────

    def append_live_reading(self, signal_scores: List[float]) -> None:
        """
        Call once per day with the current CycleDetector signal scores to keep
        the rolling history fresh for inference.

        signal_scores : [s.score for s in comp.signals]  (length = N_SIGNALS)
        """
        self._signal_history.append(signal_scores)
        # Keep only what we need plus a small buffer
        max_keep = self.seq_len + 30
        if len(self._signal_history) > max_keep:
            self._signal_history = self._signal_history[-max_keep :]
        # Persist
        self._save_history_cache()

    # ── persistence ──────────────────────────────────────────────────────────

    def _save_model(self) -> None:
        if self.model is None or not _TORCH_AVAILABLE:
            return
        self.checkpoint_path.parent.mkdir(parents=True, exist_ok=True)
        torch.save(
            {
                "state_dict": self.model.state_dict(),
                "seq_len": self.seq_len,
                "horizon": self.horizon,
                "n_signals": N_SIGNALS,
                "hidden": HIDDEN_SIZE,
                "layers": NUM_LAYERS,
            },
            self.checkpoint_path,
        )

    def _load_model(self) -> None:
        if not _TORCH_AVAILABLE:
            return
        try:
            ck = torch.load(self.checkpoint_path, map_location="cpu")
            self.seq_len = ck.get("seq_len", SEQ_LEN)
            self.horizon = ck.get("horizon", HORIZON_DEFAULT)
            n_sig   = ck.get("n_signals", N_SIGNALS)
            hidden  = ck.get("hidden",    HIDDEN_SIZE)
            layers  = ck.get("layers",    NUM_LAYERS)
            m = _CycleLSTM(input_size=n_sig, hidden=hidden, layers=layers)
            m.load_state_dict(ck["state_dict"])
            m.eval()
            self.model = m
        except Exception as e:
            print(f"[CycleAI] Could not load checkpoint ({e}); train first.")

    def _save_history_cache(self) -> None:
        try:
            self.history_cache_path.parent.mkdir(parents=True, exist_ok=True)
            keep = self._signal_history[-( self.seq_len + 30) :]
            self.history_cache_path.write_text(
                json.dumps({"signals": keep, "seq_len": self.seq_len})
            )
        except Exception:
            pass

    def _load_history_cache(self) -> None:
        if not self.history_cache_path.exists():
            return
        try:
            data = json.loads(self.history_cache_path.read_text())
            self._signal_history = data.get("signals", [])
        except Exception:
            pass


# ── standalone training script ────────────────────────────────────────────────

if __name__ == "__main__":
    print("OpenClaw V7 — AI Cycle Predictor training")
    print("==========================================")

    if not _TORCH_AVAILABLE:
        print("ERROR: PyTorch not installed.  Run:  pip install torch")
        exit(1)

    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument("--years",   type=int,   default=4,    help="Years of history to generate")
    ap.add_argument("--epochs",  type=int,   default=60,   help="Training epochs")
    ap.add_argument("--horizon", type=int,   default=30,   help="Prediction horizon (days)")
    ap.add_argument("--seq",     type=int,   default=60,   help="Input sequence length (days)")
    ap.add_argument("--out",     type=str,   default="data/ai_cycle_predictor.pth")
    args = ap.parse_args()

    predictor = CycleAIPredictor(
        checkpoint_path=args.out,
        seq_len=args.seq,
        horizon=args.horizon,
    )
    predictor.generate_and_train(years=args.years, epochs=args.epochs, verbose=True)

    # Quick sanity check
    summary = predictor.get_prediction_summary()
    print(f"\n[CycleAI] Inference test → {summary}")
